version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running Quality Checks...
      - npm run verify # Chạy ESLint và Type check của bạn
  build:
    commands:
      - echo Building the project...
      - npm run build
  post_build:
    commands:
      - echo Cleaning up...
      - npm prune --production 
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json
    - appspec.yml
    - scripts/**/*